apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitor
  namespace: argocd
spec:
  description: Monitor
  sourceRepos:
    - https://github.com/StasX/argo-gitops.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - '*'