---
# Source: AWS-Monitor/templates/service.yaml
kind: Service     
apiVersion: v1     
metadata:
  name: test-svc
spec:
  selector:
    app: test
    
    generator: helm
    name: test
  
  type: ClusterIP
  
  ports:         
  - name: http   
    protocol: TCP
    port: 80
    targetPort: 5001
---
# Source: AWS-Monitor/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    
    generator: helm
    name: test
spec:
  selector: 
    matchLabels:
      app: test
      
      generator: helm
      name: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
        
        generator: helm
        name: test
    spec:
      containers:
      - name: test
        image: sm1986/aws-monitor:1.1.6
        ports:
        - containerPort: 5001
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_ACCESS_KEY_ID

          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SECRET_ACCESS_KEY


        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
---
# Source: AWS-Monitor/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
---
# Source: AWS-Monitor/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ing
  labels:
    
    generator: helm
    name: test
spec:
  ingressClassName: nginx
  rules:
    - http:
       paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: test-svc
              port:
                 number: 80
