apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitor
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/StasX/argo-gitops.git
        revision: main
        directories:
          - path: monitor/dev
          - path: monitor/qa
          - path: monitor/prod

  template:
    metadata:
      name: 'monitor-{{path.basename}}'
    spec:
      project: monitor

      source:
        repoURL: https://github.com/StasX/argo-gitops.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true