# set at least 2 replicas
replicas: 3

ingress:
  enabled: true
  path: /qa

pod:
  targetPort: 5001
  port: 80

awsSecretName: aws-monitor-secret

externalSecret:
  enabled: false
  secretStoreName: aws-secret-store
  region: us-east-1
  awsSecretManagerName: aws-monitor


resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
    ephemeralStorage: "100Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"
    ephemeralStorage: "1Gi"

hpa:
  enabled: false
  maxReplicas: 10
  avgCPUUtilization: 50
  avgMemoryUtilization: 50

networkPolicy:
  enabled: true

pdb:
  minAvaliableReplicas: 2

podMonitor:
  enabled: true
  release: prometheus
  namespace: monitoring
  path: /qa/metrics
  interval: 15s
  scrapeTimeout: 10s

serviceMonitor:
  enabled: true
  release: prometheus
  namespace: monitoring
  path: /qa/metrics
  interval: 15s
  scrapeTimeout: 10s